version: '2'
networks:
  rabbitmq-prometheus:
volumes:
  rabbitmq-prometheus_prometheus:
  rabbitmq-prometheus_grafana:
services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: hdfcmf-prod-rabbitmq
    container_name: hdfcmf-prod-rabbitmq
    restart: always
    expose:
      - "9090"
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
    networks:
      - "rabbitmq-prometheus"
    environment:
      RABBITMQ_DEFAULT_USER: hdfcprod42
      RABBITMQ_DEFAULT_PASS: J6Ew6BeY
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
      - ./rabbitmq-data:/var/lib/rabbitmq

  rabbitmq_exporter:
    image: kbudde/rabbitmq-exporter
    depends_on:
      - "rabbitmq"
    restart: always
    ports:
      - "9999:9090"
    networks:
      - "rabbitmq-prometheus"
    environment:
      RABBIT_URL: "http://hdfcmf-prod-rabbitmq:15672"
      RABBIT_USER: "hdfcprod42"
      RABBIT_PASSWORD: "J6Ew6BeY"
      PUBLISH_PORT: "9090"
      OUTPUT_FORMAT: "JSON"
      LOG_LEVEL: "debug"

  prometheus:
    image: prom/prometheus:v1.4.1
    ports:
      - "9090:9090"
    restart: always
    networks:
      - "rabbitmq-prometheus"
    volumes:
      - rabbitmq-prometheus_prometheus:/prometheus
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - rabbitmq_exporter

  grafana:
    image: grafana/grafana
    ports:
      - "8080:3000"
    restart: always
    networks:
      - "rabbitmq-prometheus"
    volumes:
      # - rabbitmq-prometheus_grafana:/var/lib/grafana
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/rabbitmq.yaml
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/prometheus.yaml
      - ./grafana/dashboards:/dashboards
    environment:
      # https://grafana.com/plugins/flant-statusmap-panel
      # https://grafana.com/plugins/grafana-piechart-panel
      # https://grafana.com/plugins/grafana-polystat-panel
      # https://grafana.com/plugins/jdbranham-diagram-panel
      # https://grafana.com/plugins/michaeldmoore-multistat-panel
      # https://grafana.com/plugins/vonage-status-panel
      # https://grafana.com/plugins/yesoreyeram-boomtable-panel
      GF_INSTALL_PLUGINS: "flant-statusmap-panel,grafana-piechart-panel"
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "hdfc@321"
    depends_on:
      - prometheus
